Repository admiral-team/admiralui-flutter, pull requests merged in 2024-03, with the labels that each got.

#427 [381] - Chat Bubble
  example/lib/screens/chat/input/chat_input_screen.dart
  example/lib/screens/chat/input/chat_message_item.dart
  lib/admiralui_flutter.dart
  lib/src/widgets/chat/chat_bubble/chat_bubble_parameters.dart
  lib/src/widgets/chat/chat_bubble/chat_bubble_scheme.dart
  lib/src/widgets/chat/chat_bubble/chat_bubble_view.dart
  lib/src/widgets/widget_size/child_size_notifier.dart
Labels: enhancement

#431 [411, 412, 413] - Баги чата
  example/lib/screens/chat/input/chat_input_screen.dart
  example/lib/screens/chat/text_operation/text_operation_screen.dart
  example/lib/screens/chat/uploading_photo/uploading_photo_screen.dart
  lib/admiralui_flutter.dart
  lib/src/widgets/chat/chat_input/chat_input.dart
  lib/src/widgets/chat/chat_input/chat_input_file_button.dart
  lib/src/widgets/chat/chat_input/chat_input_file_button_scheme.dart
  lib/src/widgets/chat/chat_input/chat_input_scheme.dart
  lib/src/widgets/chat/uploading_photo/cell/uploading_photo_cell_item.dart
  lib/src/widgets/chat/uploading_photo/cell/uploading_photo_grid_corner_style.dart
  lib/src/widgets/chat/uploading_photo/cell/uploading_photo_item.dart
  lib/src/widgets/chat/uploading_photo/cell/uploading_photo_view.dart
  lib/src/widgets/chat/uploading_photo/cell/uploading_photo_view_scheme.dart
  lib/src/widgets/chat/uploading_photo/grid/uploading_photo_grid.dart
  lib/src/widgets/chat/uploading_photo/grid/uploading_photo_grid_builder.dart
  lib/src/widgets/controls/page_controls/circular_page_control/circular_painter.dart
Labels: bug

#429 [414] - Fix currency button screen
  example/lib/screens/currency_default_screen.dart
  example/lib/screens/currency_flags_screen.dart
  example/lib/screens/currency_icon_flags_screen.dart
  example/lib/screens/currency_icon_screen.dart
Labels: bug

#408 [374] - Вынести в определенные разделы на ruby в отдельные файлы faslane
  build/ios/fastlane/Fastfile
  build/ios/fastlane/README.md
  build/ios/fastlane/appcenter.rb
  build/ios/fastlane/deploy.rb
  build/ios/fastlane/github.rb
  build/ios/fastlane/release.rb
  build/ios/fastlane/report.xml
  build/ios/fastlane/result.rb
  build/ios/fastlane/telegram.rb
Labels: enhancement

#426 [25] - Реализовать Action Bar
  example/assets/actionBar/arrowDownOutline.png
  example/assets/actionBar/arrowUpOutline.png
  example/assets/actionBar/closeOutline.png
  example/assets/actionBar/moreOutline.png
  example/assets/actionBar/union.png
  example/lib/gen/assets.gen.dart
  example/lib/screens/cells/action_cell_screen.dart
  example/pubspec.yaml
  lib/admiralui_flutter.dart
  lib/src/widgets/views/cell/action/actions.dart
  lib/src/widgets/views/cell/base_cell.dart
  lib/src/widgets/views/cell/center/title_more_detail_text_message_widget/title_more_detail_text_message_widget.dart
  lib/src/widgets/views/cell/trailing/subtitle_image_list_widget/subtitle_image_list_widget.dart
  lib/src/widgets/views/cell/trailing/subtitle_image_list_widget/subtitle_image_list_widget_scheme.dart
  test/goldens/home_page.iPad.png
  test/goldens/home_page.iPhone 14.png
  test/goldens/home_page.iPhone SE.png
Labels: enhancement

#453 [452] - Добавить provision profile для remote_demo iOS
  .github/workflows/dart.yml
  remote_demo/ios/Runner.xcodeproj/project.pbxproj
  remote_demo/ios/Runner/Info.plist
Labels: enhancement

#454 [445] - Fix init state for circular & linear page controll
  example/lib/screens/pageControls/circle/page_control_circle_screen.dart
  example/lib/screens/pageControls/linear/page_control_linear_screen.dart
  lib/src/widgets/tabs/outline_tabs/outline_tabs.dart
Labels: bug

#457 [415] - Slider Line Width
  lib/admiralui_flutter.dart
  lib/src/widgets/controls/sliders/double_slider_widget.dart
  lib/src/widgets/controls/sliders/slider_line_painter.dart
  lib/src/widgets/controls/sliders/slider_widget.dart
Labels: bug

#480 [TECH] - Fix set version
  build/ios/fastlane/Fastfile
  build/ios/fastlane/release.rb
Labels: bug, enhancement
